import { RankedListing, TrustReport } from './types';

export const mockListings: RankedListing[] = [
  {
    rank: 1,
    id: 'L034',
    title: '2BHK 100 Ft Road',
    rent: 34000,
    score: 87,
    verdict: 'SAFE',
    one_liner: 'Original photos, fair price, 18-min commute',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 2,
    id: 'L035',
    title: '2BHK 12th Main',
    rent: 33000,
    score: 82,
    verdict: 'SAFE',
    one_liner: 'Broker verified, great location',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a92bde50b?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 3,
    id: 'L036',
    title: '2BHK CMH Road',
    rent: 35000,
    score: 79,
    verdict: 'SAFE',
    one_liner: 'Consistent pricing, verified owner',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9b2b17b20dff?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 4,
    id: 'L037',
    title: '2BHK Jeevan Bima Nagar',
    rent: 32000,
    score: 68,
    verdict: 'CAUTION',
    one_liner: 'Missing some interior photos',
    imageUrl: 'https://images.unsplash.com/photo-1494145904049-0dca7dc20e59?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Jeevan Bima Nagar',
    pincode: '560075',
  },
  {
    rank: 5,
    id: 'L038',
    title: '2BHK HAL 2nd Stage',
    rent: 31000,
    score: 61,
    verdict: 'CAUTION',
    one_liner: 'Below market rent, needs visit',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'HAL 2nd Stage',
    pincode: '560008',
  },
  {
    rank: 6,
    id: 'L039',
    title: '2BHK Domlur border',
    rent: 30000,
    score: 55,
    verdict: 'CAUTION',
    one_liner: 'Unresponsive agent',
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18ecbc563b8?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Domlur',
    pincode: '560071',
  },
  {
    rank: 7,
    id: 'L040',
    title: '2BHK "Prime Indiranagar"',
    rent: 24000,
    score: 34,
    verdict: 'HIGH_RISK',
    one_liner: 'Extremely underpriced',
    imageUrl: 'https://images.unsplash.com/photo-1494145904049-0dca7dc20e59?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 8,
    id: 'L041',
    title: '2BHK "Spacious, near metro"',
    rent: 22000,
    score: 28,
    verdict: 'HIGH_RISK',
    one_liner: 'Stock photos used',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 9,
    id: 'L091',
    title: '2BHK "Owner going abroad"',
    rent: 18000,
    score: 18,
    verdict: 'HIGH_RISK',
    one_liner: 'Stolen photo + 49% below market + scam language',
    imageUrl: 'https://images.unsplash.com/photo-1509652345193-eb4124d6e3f2?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 10,
    id: 'L042',
    title: '2BHK "Urgent, token to hold"',
    rent: 16000,
    score: 12,
    verdict: 'HIGH_RISK',
    one_liner: 'Urgency tactics, extreme bait pricing',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9b2b17b20dff?w=400&h=300&fit=crop',
    bhk: '2BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
];

export const mockTrustReports: Record<string, TrustReport> = {
  'L034': {
    listing_id: 'L034',
    score: 87,
    verdict: 'SAFE',
    flags: [
      {
        agent: 'price',
        verdict: 'CLEAN',
        detail: 'Rent is market-aligned for Indiranagar 2BHK',
        evidence: [
          'Average rent in area: 32k-35k',
          'Premium location justifies price',
        ],
        confidence: 98,
        weight: 1,
      },
      {
        agent: 'photo',
        verdict: 'CLEAN',
        detail: 'Photos are recent and represent actual property',
        evidence: [
          'Multiple high-quality images',
          'Consistent lighting and staging',
          'No obvious duplicates detected',
        ],
        confidence: 92,
        weight: 1,
      },
    ],
    reasoning: [
      'Listing passes all five-agent verification checks',
      'Price is consistent with local market data',
      'Documentation appears legitimate and complete',
      'No indicators of bait-and-switch or fraud tactics',
    ],
    questions_to_ask: [
      'Can the landlord provide recent utility bills as proof of residence?',
      'Is the property registered with municipality? Can you share registration documents?',
      'What is the lease renewal process and any additional charges?',
    ],
  },
  'L091': {
    listing_id: 'L091',
    score: 18,
    verdict: 'HIGH_RISK',
    flags: [
      {
        agent: 'photo',
        verdict: 'SUSPICIOUS',
        detail: 'Photo #2 is STOLEN — appears on Hyderabad + Pune listings',
        evidence: ['nobroker.in/hyd/...', '99acres.com/pune/...'],
        confidence: 99,
        weight: 1,
      },
      {
        agent: 'price',
        verdict: 'BAIT',
        detail: 'Rent ₹18,000 is 49% BELOW the ₹35,000 area median',
        evidence: ['median ₹35,000'],
        confidence: 99,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'LIE',
        detail: 'Claims 5 min to metro; real 9AM is 21 min; office 47 min',
        evidence: ['21 min', '47 min'],
        confidence: 99,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'SUSPICIOUS',
        detail: 'Scam language: "owner abroad", "pay token to hold", "WhatsApp me directly"',
        evidence: ['owner abroad', 'pay token', 'WhatsApp me'],
        confidence: 94,
        weight: 1,
      },
    ],
    reasoning: [
      'Price flagged 49% underpriced → escalated Photo to deep scan',
      'Photo found Hyderabad-origin image → handed conflict to Commute',
      'Conflict: photos clean but price+text flag scam',
      'Arbiter hypothesis: photo stolen recently, not yet web-indexed',
      'Re-dispatched Photo with within-batch dedup → duplicate found',
      'Resolved: HIGH RISK',
    ],
    questions_to_ask: [
      'Can I video-call live from inside the flat right now?',
      'Why is the rent so far below other 2BHKs here?',
      'Can I pay strictly after a physical visit — no token?',
    ],
  },
};
