import { RankedListing, TrustReport } from './types';

export const mockListings: RankedListing[] = [
  {
    rank: 1,
    id: 'listing-1',
    title: 'Spacious 2BHK with Balcony - Indiranagar',
    rent: 34000,
    score: 87,
    verdict: 'SAFE',
    one_liner: 'Well-maintained, responsive landlord, verified documents',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Indiranagar',
    pincode: '560038',
  },
  {
    rank: 2,
    id: 'listing-2',
    title: '2BHK Flat in Koramangala - Near Metro',
    rent: 32500,
    score: 76,
    verdict: 'SAFE',
    one_liner: 'Prime location, modern amenities, transparent lease',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a92bde50b?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Koramangala',
    pincode: '560034',
  },
  {
    rank: 3,
    id: 'listing-3',
    title: '2BHK Apartment - Whitefield',
    rent: 28000,
    score: 72,
    verdict: 'SAFE',
    one_liner: 'New construction, all amenities, easy commute',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9b2b17b20dff?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Whitefield',
    pincode: '560066',
  },
  {
    rank: 4,
    id: 'listing-4',
    title: '2BHK in Marathahalli - Furnished',
    rent: 24500,
    score: 62,
    verdict: 'CAUTION',
    one_liner: 'Furnished but several agent contact attempts before response',
    imageUrl: 'https://images.unsplash.com/photo-1494145904049-0dca7dc20e59?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Marathahalli',
    pincode: '560037',
  },
  {
    rank: 5,
    id: 'listing-5',
    title: '2BHK Duplex - Bellandur',
    rent: 26000,
    score: 58,
    verdict: 'CAUTION',
    one_liner: 'Rent suspiciously low for area, limited photos provided',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Bellandur',
    pincode: '560103',
  },
  {
    rank: 6,
    id: 'listing-6',
    title: 'Owner Going Abroad - 2BHK Flat',
    rent: 18000,
    score: 18,
    verdict: 'HIGH_RISK',
    one_liner: 'Classic bait & switch scam - price unrealistic, vague photos',
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18ecbc563b8?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Jayanagar',
    pincode: '560011',
  },
  {
    rank: 7,
    id: 'listing-7',
    title: '2BHK - Immediate Possession - Urgent',
    rent: 21000,
    score: 28,
    verdict: 'HIGH_RISK',
    one_liner: 'Excessive urgency, reused photos from other listings, no address',
    imageUrl: 'https://images.unsplash.com/photo-1494145904049-0dca7dc20e59?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'HSR Layout',
    pincode: '560034',
  },
  {
    rank: 8,
    id: 'listing-8',
    title: '2BHK Apartment - Frazer Town',
    rent: 30000,
    score: 68,
    verdict: 'SAFE',
    one_liner: 'Good condition, responsive owner, verified landlord',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Frazer Town',
    pincode: '560005',
  },
  {
    rank: 9,
    id: 'listing-9',
    title: '2BHK in Richmond Town - Heritage Area',
    rent: 28500,
    score: 65,
    verdict: 'SAFE',
    one_liner: 'Historic building, well-maintained, trustworthy landlord',
    imageUrl: 'https://images.unsplash.com/photo-1509652345193-eb4124d6e3f2?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Richmond Town',
    pincode: '560025',
  },
  {
    rank: 10,
    id: 'listing-10',
    title: '2BHK - No Brokerage - Same Tenant Since 5 Yrs',
    rent: 22000,
    score: 45,
    verdict: 'CAUTION',
    one_liner: 'Outdated photos, slow communication, inconsistent lease terms',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9b2b17b20dff?w=400&h=300&fit=crop',
    bhk: '2 BHK',
    area: 'Shantinagar',
    pincode: '560027',
  },
];

export const mockTrustReports: Record<string, TrustReport> = {
  'listing-1': {
    listing_id: 'listing-1',
    score: 87,
    verdict: 'SAFE',
    flags: [
      {
        agent: 'price',
        verdict: 'CLEAN',
        detail: 'Rent is market-aligned for Indiranagar 2BHK',
        evidence: [
          'Average rent in area: 32k-35k',
          'Premium location justifies price',
        ],
        confidence: 98,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'CLEAN',
        detail: 'Listing language is professional and complete',
        evidence: [
          'All required details provided',
          'No urgency tactics or red flags in description',
        ],
        confidence: 95,
        weight: 1,
      },
      {
        agent: 'photo',
        verdict: 'CLEAN',
        detail: 'Photos are recent and represent actual property',
        evidence: [
          'Multiple high-quality images',
          'Consistent lighting and staging',
          'No obvious duplicates detected',
        ],
        confidence: 92,
        weight: 1,
      },
      {
        agent: 'web',
        verdict: 'CLEAN',
        detail: 'Owner has positive online footprint',
        evidence: [
          'Verified landlord profile on multiple platforms',
          'No complaints or fraud reports found',
        ],
        confidence: 90,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'CLEAN',
        detail: 'Location verified as legitimate residential area',
        evidence: [
          'Confirmed proximity to metro stations',
          'Accessible public transport',
        ],
        confidence: 97,
        weight: 1,
      },
    ],
    reasoning: [
      'Listing passes all five-agent verification checks',
      'Price is consistent with local market data',
      'Documentation appears legitimate and complete',
      'Owner profile shows sustained rental history',
      'No indicators of bait-and-switch or fraud tactics',
    ],
    questions_to_ask: [
      'Can the landlord provide recent utility bills as proof of residence?',
      'Is the property registered with municipality? Can you share registration documents?',
      'What is the lease renewal process and any additional charges?',
    ],
  },
  'listing-2': {
    listing_id: 'listing-2',
    score: 76,
    verdict: 'SAFE',
    flags: [
      {
        agent: 'price',
        verdict: 'CLEAN',
        detail: 'Price is competitive for Koramangala location',
        evidence: [
          'Comparable listings in range 31k-34k',
          'Modern amenities justify premium',
        ],
        confidence: 94,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'CLEAN',
        detail: 'Listing contains complete property details',
        evidence: [
          'Amenities clearly listed',
          'Contact information verified',
        ],
        confidence: 91,
        weight: 1,
      },
      {
        agent: 'photo',
        verdict: 'SUSPICIOUS',
        detail: 'One interior photo appears slightly different from main images',
        evidence: [
          'Lighting inconsistency in one image',
          'Could indicate minor editing',
        ],
        confidence: 65,
        weight: 0.5,
      },
      {
        agent: 'web',
        verdict: 'CLEAN',
        detail: 'Owner verified across multiple rental platforms',
        evidence: ['Good feedback history', 'No red flags in previous tenancies'],
        confidence: 89,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'CLEAN',
        detail: 'Premium location near Metro Station',
        evidence: [
          'Walking distance to Koramangala Metro',
          'Excellent restaurant and shopping proximity',
        ],
        confidence: 96,
        weight: 1,
      },
    ],
    reasoning: [
      'Overall profile is positive with minor photographic inconsistency',
      'Price supported by comparable market data',
      'Owner has established rental history',
      'Location benefits justify premium pricing',
      'Minor photo quality issue does not indicate fraud',
    ],
    questions_to_ask: [
      'Can I schedule multiple viewings at different times of day?',
      'What is the tenant screening process? Any background check required?',
      'Are utilities typically higher in this building compared to similar properties?',
    ],
  },
  'listing-3': {
    listing_id: 'listing-3',
    score: 72,
    verdict: 'SAFE',
    flags: [
      {
        agent: 'price',
        verdict: 'CLEAN',
        detail: 'Market-aligned pricing for new construction',
        evidence: [
          'Whitefield rates: 26k-30k for similar units',
          'New amenities justify rate',
        ],
        confidence: 93,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'CLEAN',
        detail: 'Well-structured listing with clear details',
        evidence: [
          'Amenity list is comprehensive',
          'Lease terms clearly outlined',
        ],
        confidence: 90,
        weight: 1,
      },
      {
        agent: 'photo',
        verdict: 'CLEAN',
        detail: 'Professional photography of new construction',
        evidence: [
          'High-quality images provided',
          'Multiple angles and rooms shown',
        ],
        confidence: 94,
        weight: 1,
      },
      {
        agent: 'web',
        verdict: 'CLEAN',
        detail: 'Builder and agent are registered',
        evidence: [
          'Verified developer credentials',
          'Agent has valid license',
        ],
        confidence: 88,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'CLEAN',
        detail: 'Whitefield location offers good IT corridor access',
        evidence: [
          'Close to tech parks',
          'Metro expansion planned for area',
        ],
        confidence: 91,
        weight: 1,
      },
    ],
    reasoning: [
      'New construction offers good value proposition',
      'All verification agents report clean status',
      'Builder has solid reputation in region',
      'Modern amenities provide competitive advantage',
      'Reasonable commute to major employment centers',
    ],
    questions_to_ask: [
      'Are there any pending environmental or structural certifications?',
      'What is the maintenance charge structure? Is it locked for years?',
      'Can you provide possession certificate and buyer-seller agreement samples?',
    ],
  },
  'listing-6': {
    listing_id: 'listing-6',
    score: 18,
    verdict: 'HIGH_RISK',
    flags: [
      {
        agent: 'price',
        verdict: 'BAIT',
        detail: 'Price is significantly below market - classic bait & switch',
        evidence: [
          'Jayanagar avg rent: 26k-31k',
          'Listed at 18k - 45% below market',
          'Unrealistic pricing indicates scam',
        ],
        confidence: 99,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'SUSPICIOUS',
        detail: 'Listing uses common scam phrases',
        evidence: [
          'Owner going abroad (classic scam trigger)',
          'Vague property description',
          'Missing key amenity details',
        ],
        confidence: 94,
        weight: 1,
      },
      {
        agent: 'photo',
        verdict: 'BAIT',
        detail: 'Photos appear to be stock images',
        evidence: [
          'Reverse image search matches other listings',
          'Inconsistent furniture styles across rooms',
          'Professional photoshoot quality suggests generic stock images',
        ],
        confidence: 97,
        weight: 1,
      },
      {
        agent: 'web',
        verdict: 'LIE',
        detail: 'Owner profile shows fraud indicators',
        evidence: [
          'Account created recently (7 days ago)',
          'Multiple fraud reports filed against this account',
          'Previous victims mentioned advance payment requests',
        ],
        confidence: 99,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'SUSPICIOUS',
        detail: 'Address verification failed',
        evidence: [
          'Provided address does not exist in Google Maps',
          'Postal code mismatch for area',
        ],
        confidence: 92,
        weight: 1,
      },
    ],
    reasoning: [
      'Multiple red flags indicate coordinated scam operation',
      'Price far below market is primary bait mechanism',
      'Photos are demonstrably reused stock images',
      'Owner account has active fraud reports',
      'This listing exhibits all hallmarks of advance payment scam',
      'DO NOT contact or provide any personal/financial information',
    ],
    questions_to_ask: [
      'Ask to speak directly with property owner (not agent)',
      'Request property address and visit in person before any payments',
      'Never send advance payment or deposit without seeing property',
    ],
  },
  'listing-4': {
    listing_id: 'listing-4',
    score: 62,
    verdict: 'CAUTION',
    flags: [
      {
        agent: 'price',
        verdict: 'CLEAN',
        detail: 'Price is reasonable for furnished 2BHK',
        evidence: [
          'Furnished units command premium',
          'Within expected range for Marathahalli',
        ],
        confidence: 85,
        weight: 1,
      },
      {
        agent: 'text',
        verdict: 'SUSPICIOUS',
        detail: 'Limited property details provided',
        evidence: [
          'Amenities not fully described',
          'Lease terms unclear',
        ],
        confidence: 72,
        weight: 0.7,
      },
      {
        agent: 'photo',
        verdict: 'CLEAN',
        detail: 'Photos appear legitimate',
        evidence: ['Recent property images', 'Consistent lighting'],
        confidence: 80,
        weight: 1,
      },
      {
        agent: 'web',
        verdict: 'SUSPICIOUS',
        detail: 'Agent required multiple contact attempts for response',
        evidence: [
          'Slow response time (24+ hours)',
          'May indicate low engagement with listings',
        ],
        confidence: 68,
        weight: 0.6,
      },
      {
        agent: 'commute',
        verdict: 'CLEAN',
        detail: 'Marathahalli location verified',
        evidence: [
          'Good IT corridor access',
          'Metro connectivity available',
        ],
        confidence: 90,
        weight: 1,
      },
    ],
    reasoning: [
      'No major red flags but communication issues noted',
      'Agent responsiveness is below average',
      'Property details could be more comprehensive',
      'Price and location are reasonable',
      'Recommended: Request detailed amenity list before committing',
    ],
    questions_to_ask: [
      'What exactly is included in the furnished setup? Can items be removed?',
      'What is the typical response time for maintenance requests?',
      'Are there any restrictions on guests or parties?',
    ],
  },
  'listing-5': {
    listing_id: 'listing-5',
    score: 58,
    verdict: 'CAUTION',
    flags: [
      {
        agent: 'price',
        verdict: 'BAIT',
        detail: 'Price is 20-25% below market for Bellandur',
        evidence: [
          'Bellandur avg: 32k-38k for 2BHK',
          'Listed at 26k appears discounted',
          'Possible bait tactic',
        ],
        confidence: 78,
        weight: 0.8,
      },
      {
        agent: 'text',
        verdict: 'SUSPICIOUS',
        detail: 'Limited photographic evidence provided',
        evidence: [
          'Only 3 photos vs typical 8-12',
          'Some rooms not shown',
        ],
        confidence: 75,
        weight: 0.7,
      },
      {
        agent: 'photo',
        verdict: 'SUSPICIOUS',
        detail: 'Photo count and quality suggest incomplete property documentation',
        evidence: ['Few exterior shots', 'No amenity photos'],
        confidence: 70,
        weight: 0.7,
      },
      {
        agent: 'web',
        verdict: 'CLEAN',
        detail: 'Owner profile is established',
        evidence: [
          'Account active for 2+ years',
          'No fraud complaints',
        ],
        confidence: 82,
        weight: 1,
      },
      {
        agent: 'commute',
        verdict: 'CLEAN',
        detail: 'Bellandur is legitimate locality',
        evidence: [
          'IT park proximity',
          'Good transport connectivity',
        ],
        confidence: 88,
        weight: 1,
      },
    ],
    reasoning: [
      'Price discount suggests need for verification',
      'Limited photos may indicate owner reluctance or low quality',
      'Owner profile is generally trustworthy',
      'Recommend thorough site inspection before commitment',
      'Clarify reason for below-market pricing',
    ],
    questions_to_ask: [
      'Why is the rental rate lower than comparable properties in the area?',
      'Can the owner provide additional photos of all rooms and amenities?',
      'What are the reasons for the recent vacancy?',
    ],
  },
};
